remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Welcome to Virginia Beach Adult Gymnastics Club (VBAGC)!
description: Hampton Roads' only adult gymnastics club for all ages, genders, and skill levels!
show_downloads: true
google_analytics: [Your Google Analytics tracking ID]

