remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Welcome to Virginia Beach Adult Gymnastics Club (VBAGC)!
description: Hampton Roads' only adult gymnastics club for all ages, genders, and skill levels!
show_downloads: true
google_analytics: G-V899YXR1G6
logo: "https://user-images.githubusercontent.com/108369432/225924539-667de481-c5aa-4c4e-a5a1-412f92b4a192.JPG"

